# Generated by Django 5.0.14 on 2026-01-07 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="min_stock",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="product",
            name="qrcode_image",
            field=models.ImageField(blank=True, null=True, upload_to="qrcodes/"),
        ),
    ]
